In [1]:
import numpy as np


In [2]:
a1=np.array([1,2,3,4,5])
a1

array([1, 2, 3, 4, 5])

In [3]:
a2=np.array([[1,2,3,4,5],[9,8,7,6,5],[4,5,6,7,8],[1,9,2,8,3]])
a2


array([[1, 2, 3, 4, 5],
       [9, 8, 7, 6, 5],
       [4, 5, 6, 7, 8],
       [1, 9, 2, 8, 3]])

In [4]:
a3=np.array([[[1,2,3,4,5],[1,2,3,4,5]],
           [[1,2,3,4,5],[1,2,3,4,5]]])
a3

array([[[1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5]],

       [[1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5]]])

In [5]:
a1.shape,a2.shape,a3.shape

((5,), (4, 5), (2, 2, 5))

In [6]:
a1.dimen,a2.dimen,a3.dimen

AttributeError: 'numpy.ndarray' object has no attribute 'dimen'

In [ ]:
a1.dtype,a2.dtype,a3.dtype

In [ ]:
a1.size,a2.size,a3.size

In [ ]:
type(a1),type(a2),type(a3)

In [7]:
a1.ndim,a2.ndim,a3.ndim

(1, 2, 3)

In [8]:
import pandas  as pd

In [9]:
dt1=pd.DataFrame(a1)
dt

NameError: name 'dt' is not defined

In [ ]:
one=np.ones((10,2))
one

In [ ]:
zero=np.zeros((7,2,3))
zero

In [ ]:
r1=np.arange(0,100,3)
r1

In [10]:
r2=np.random.randint(0,10,size=(4,6))
r2

array([[8, 2, 0, 8, 2, 3],
       [8, 1, 0, 0, 3, 7],
       [3, 0, 1, 5, 9, 1],
       [7, 2, 0, 8, 4, 7]])

In [11]:
r3=np.random.random((3,5))
r3

array([[0.42497414, 0.60858404, 0.22562254, 0.05129271, 0.59456559],
       [0.78494765, 0.7219118 , 0.79379534, 0.58071047, 0.47464858],
       [0.46723742, 0.67386096, 0.55560984, 0.28772863, 0.01935291]])

In [12]:
np.random.seed(42)
r4=np.random.randint(0,10,size=(4,6))
r4

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

In [13]:
r5=np.random.randint(1,10,size=(3,7))
r5

array([[9, 1, 3, 7, 4, 9, 3],
       [5, 3, 7, 5, 9, 7, 2],
       [4, 9, 2, 9, 5, 2, 4]])

In [17]:
np.unique(r5)

array([1, 2, 3, 4, 5, 7, 9])

In [18]:
r5[0]

array([9, 1, 3, 7, 4, 9, 3])

In [27]:
r5[:2]

array([[9, 1],
       [5, 3]])

In [28]:
r5[:2,:2]

array([[9, 1],
       [5, 3]])

In [30]:
r6=np.random.randint(0,10,size=(3,5))
o=np.ones((3,5))
r6,o

(array([[9, 1, 9, 3, 7],
        [6, 8, 7, 4, 1],
        [4, 7, 9, 8, 8]]),
 array([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]))

In [31]:
r6+o

array([[10.,  2., 10.,  4.,  8.],
       [ 7.,  9.,  8.,  5.,  2.],
       [ 5.,  8., 10.,  9.,  9.]])

In [32]:
o2=np.ones((5,3))
o2

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [34]:
o2+o.T

array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])

In [35]:
o3=np.ones((3,5))
o3

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [37]:
o3-o

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [38]:
o*(o3-o)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [40]:
r6**2

array([[81,  1, 81,  9, 49],
       [36, 64, 49, 16,  1],
       [16, 49, 81, 64, 64]])

In [41]:
np.square(r6)

array([[81,  1, 81,  9, 49],
       [36, 64, 49, 16,  1],
       [16, 49, 81, 64, 64]])

In [42]:
np.mean(o)

1.0

In [44]:
np.max(r6)
r6

array([[9, 1, 9, 3, 7],
       [6, 8, 7, 4, 1],
       [4, 7, 9, 8, 8]])

In [45]:
np.min(r6)

1

In [49]:
np.std(r6)

2.6948510575210314

In [47]:
np.var(r6)

7.262222222222222

In [52]:
r6=np.reshape(o2,(3,5,1))
r6

array([[[1.],
        [1.],
        [1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.],
        [1.],
        [1.]]])

In [53]:
r6.T


array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [55]:
rr=np.random.randint(10,size=(3,3))
rr

array([[0, 8, 6],
       [8, 7, 0],
       [7, 7, 2]])

In [57]:
rr1=np.random.randint(10,size=(3,2))
rr1

array([[0, 7],
       [2, 2],
       [0, 4]])

In [58]:
rr.dot(rr1)

array([[16, 40],
       [14, 70],
       [14, 71]])

In [61]:
rr2=np.random.randint(0,10,size=(4,3))
rr2

array([[9, 6, 9],
       [8, 6, 8],
       [7, 1, 0],
       [6, 6, 7]])

In [63]:
rr3=np.random.randint(0,10,size=(4,3))
rr3

array([[6, 6, 8],
       [9, 9, 2],
       [6, 0, 3],
       [3, 4, 6]])

In [66]:
rr2.dot(rr3.T)

array([[162, 153,  81, 105],
       [148, 142,  72,  96],
       [ 48,  72,  42,  25],
       [128, 122,  57,  84]])

In [67]:
rr3>rr2

array([[False, False, False],
       [ True,  True, False],
       [False, False,  True],
       [False, False, False]])

In [68]:
rr3>=rr2

array([[False,  True, False],
       [ True,  True, False],
       [False, False,  True],
       [False, False, False]])

In [69]:
rr2>=7

array([[ True, False,  True],
       [ True, False,  True],
       [ True, False, False],
       [False, False,  True]])

In [70]:
rr3==rr2

array([[False,  True, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [79]:
rr2

array([[6, 9, 9],
       [6, 8, 8],
       [0, 1, 7],
       [6, 6, 7]])

In [100]:
np.sort(rr2)


array([[6, 9, 9],
       [6, 8, 8],
       [0, 1, 7],
       [6, 6, 7]])

In [102]:
np.argsort(rr2)

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]], dtype=int64)

In [104]:
np.argmin(rr2,axis=0)

array([2, 2, 2], dtype=int64)

In [105]:
np.argmax(rr2,
          axis=1)

array([1, 1, 2, 2], dtype=int64)

In [98]:
rr3=np.arange(1,100,10)
rr3

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [99]:
np.random.randn(3,5)

array([[ 0.8727051 ,  2.28722598,  1.6229205 ,  0.82373308,  0.29305925],
       [ 0.89663038, -0.61032202, -0.3161659 , -1.48242425, -0.22884752],
       [ 0.96264129, -0.20969244, -0.77404293, -0.35977815,  0.72408325]])